
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BEDO
 */
public class Numerical_Solutions extends javax.swing.JFrame {

    /**
     * Creates new form Numerical_Solutions
     */
    public Numerical_Solutions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        answer = new javax.swing.JTextArea();
        button3 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        matrix = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        out = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Answer =");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 310, 130, 60);

        filename.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        filename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filenameActionPerformed(evt);
            }
        });
        filename.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                filenamePropertyChange(evt);
            }
        });
        jPanel2.add(filename);
        filename.setBounds(220, 40, 190, 40);

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("File Name :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 30, 130, 60);

        button1.setLabel("Inversion");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel2.add(button1);
        button1.setBounds(470, 190, 130, 40);

        button2.setLabel("Gaussian");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel2.add(button2);
        button2.setBounds(470, 130, 130, 40);

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Matrix =");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 140, 130, 60);

        answer.setEditable(false);
        answer.setColumns(20);
        answer.setRows(5);
        jScrollPane1.setViewportView(answer);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(220, 310, 190, 90);

        button3.setLabel("Exit");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel2.add(button3);
        button3.setBounds(470, 330, 130, 40);

        matrix.setEditable(false);
        matrix.setColumns(20);
        matrix.setRows(5);
        jScrollPane2.setViewportView(matrix);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(220, 130, 130, 100);

        out.setEditable(false);
        out.setColumns(20);
        out.setRows(5);
        jScrollPane3.setViewportView(out);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(360, 130, 50, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/erase.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filenameActionPerformed

    private void filenamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_filenamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_filenamePropertyChange

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        String filename=this.filename.getText();   
        SolutionContext slt1 = null;
        try {
            slt1 = new SolutionContext(filename);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR...There is no filename like this !!!");
            ex.toString();
            //Logger.getLogger(Numerical_Solutions.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(slt1.get_satir()==slt1.get_sutun() && slt1.flag){
               
            this.matrix.setText(slt1.display_matrix());
            this.out.setText(slt1.display_out());
            slt1.setSolution(new GaussianStrategy());
            slt1.creatSolution();
            this.answer.setText(slt1.output);
        }else{
            if(slt1.flag==false){
                 JOptionPane.showMessageDialog(this, "ERROR...There is no filename like this !!!"); 
            }else{  
              JOptionPane.showMessageDialog(this, "ERROR...The Matrix type is not appropriate !!!");
            }

        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String filename=this.filename.getText();   
        SolutionContext slt1 = null;
        try {
            slt1 = new SolutionContext(filename);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "ERROR...There is no filename like this !!!");
            ex.toString();
           // Logger.getLogger(Numerical_Solutions.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(slt1.get_satir()==slt1.get_sutun() && slt1.flag){              
            this.matrix.setText(slt1.display_matrix());
            this.out.setText(slt1.display_out());
            slt1.setSolution(new MatrixInversion());
            slt1.creatSolution();
            this.answer.setText(slt1.output);
        }else{
            if(slt1.flag==false){
                 JOptionPane.showMessageDialog(this, "ERROR...There is no filename like this !!!"); 
            }else{  
              JOptionPane.showMessageDialog(this, "ERROR...The Matrix type is not appropriate !!!");
            }

        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Numerical_Solutions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Numerical_Solutions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Numerical_Solutions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Numerical_Solutions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Numerical_Solutions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answer;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private javax.swing.JTextField filename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea matrix;
    private javax.swing.JTextArea out;
    // End of variables declaration//GEN-END:variables
}
